### ISSUE TITLE
Use POST/PUT/PATCH methods

### ISSUE THREAD

**Issue by lantushenkoao** [wwllaad/station-passport#4]
https://github.com/wwllaad/station-passport/blob/8c1aabdf4d27e5a4d2b364d7f26dfd7614ed19e9/src/main/java/com/sevgmo/stationpassport/controller/RestController.java#L39

GET http method should be used only to retrieve some information. All database updates should be done via POST (or PATCH, PUT, etc)

**Comment by wwllaad** [comment]
Done.

**Comment by lantushenkoao** [comment]
nope :) I still only see GetMapping annotations in controller
